### PR TITLE
[zoom] new extractor

### LINKED ISSUE #107: need zoomus extractor
Please integrate it in `yt-dlc`. It is working properly.

https://github.com/ytdl-org/youtube-dl/pull/24751

### PR DESCRIPTION
**Pull request by insaneracist**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

Fixes #107 
Original pull request: https://github.com/unqueued/youtube-dl-prs/tree/pr/24751
I think the password field detection needs updating, however it downloads public videos.

### CODE REVIEW

**Comment by someziggyman** [comment]
seems to be working fine with all the Zoom links I've tried. Public and a couple password protected. Good job!

**Comment by insaneracist** [comment]
shouldn't this extractor be called `zoom` rather than `zoomus`?

**Comment by blackjack4494** [comment]
> shouldn't this extractor be called `zoom` rather than `zoomus`?

yup

**Review by blackjack4494 — APPROVED** [review]

**Comment by someziggyman** [comment]
While this awesome extractor seems to be working fine, I've come across this password protected link today and it seems to have some custom theme on the page. Extractor does not see or identify it as one it can handle. Don't have a password to it yet to test if it works with --password parameter forced. 

https://shopify.zoom.us/rec/share/J_bW4XEaoXCiUUP-oJjnMKF48xFhF8PMBJes_8pcLWqr8P3b1Xf0ljwz06Wxk2j5.N5Ed9tm6fJNI5BxA

Please see the log below:
_./testdlc -F -v https://shopify.zoom.us/rec/share/J_bW4XEaoXCiUUP-oJjnMKF48xFhF8PMBJes_8pcLWqr8P3b1Xf0ljwz06Wxk2j5.N5Ed9tm6fJNI5BxA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'https://shopify.zoom.us/rec/share/J_bW4XEaoXCiUUP-oJjnMKF48xFhF8PMBJes_8pcLWqr8P3b1Xf0ljwz06Wxk2j5.N5Ed9tm6fJNI5BxA']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] J_bW4XEaoXCiUUP-oJjnMKF48xFhF8PMBJes_8pcLWqr8P3b1Xf0ljwz06Wxk2j5: Requesting header
WARNING: Falling back on generic information extractor.
[generic] J_bW4XEaoXCiUUP-oJjnMKF48xFhF8PMBJes_8pcLWqr8P3b1Xf0ljwz06Wxk2j5: Downloading webpage
[generic] J_bW4XEaoXCiUUP-oJjnMKF48xFhF8PMBJes_8pcLWqr8P3b1Xf0ljwz06Wxk2j5: Extracting information
ERROR: Unsupported URL: https://shopify.zoom.us/rec/share/J_bW4XEaoXCiUUP-oJjnMKF48xFhF8PMBJes_8pcLWqr8P3b1Xf0ljwz06Wxk2j5.N5Ed9tm6fJNI5BxA
Traceback (most recent call last):
  File "./testdlc/youtube_dlc/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./testdlc/youtube_dlc/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./testdlc/youtube_dlc/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "./testdlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "./testdlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "./testdlc/youtube_dlc/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://shopify.zoom.us/rec/share/J_bW4XEaoXCiUUP-oJjnMKF48xFhF8PMBJes_8pcLWqr8P3b1Xf0ljwz06Wxk2j5.N5Ed9tm6fJNI5BxA_

**Pull request merged**
