### PR TITLE
[instagram] Fix extractor

### PR DESCRIPTION
**Pull request by nao20010128nao**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This is taken from youtube-dl PR ytdl-org/youtube-dl#26981
https://github.com/unqueued/youtube-dl-prs/commit/f7960affb7f51cb5cb7671031028cb9b1499b50e

Original instagram.py is from https://github.com/nao20010128nao/ytdl-patched/blob/master/youtube_dl/extractor/instagram.py

### CODE REVIEW

**Comment by blackjack4494** [comment]
@nao20010128nao what problems do you have?
Can you provide some sample links which don't work with current version but will with your changes?

**Comment by nao20010128nao** [comment]
@blackjack4494 
All post URLs are affected, but here's an example: https://www.instagram.com/p/CHSZ6YAosQS/

**Comment by blackjack4494** [comment]
@nao20010128nao 
```
PS D:\gitkraken\yt-dlc> python3 -m youtube_dlc "https://www.instagram.com/p/CHSZ6YAosQS/" -v -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.instagram.com/p/CHSZ6YAosQS/', '-v', '-F']
[debug] Loading archive file None
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dlc version 2020.10.25
[debug] Git HEAD: f406ab6a1
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[Instagram] CHSZ6YAosQS: Downloading webpage
[info] Available formats for CHSZ6YAosQS:
format code  extension  resolution note
0            mp4        750x937
```
I am confused. This is on current master :D

**Comment by nao20010128nao** [comment]
@blackjack4494 I did the (mostly) same, but it fails on my side.

**Comment by blackjack4494** [comment]
```
[Instagram] CHSZ6YAosQS: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
[info] Available formats for CHSZ6YAosQS:
```
The warning needs to be handled @nao20010128nao 
then it should be good to go.

**Comment by nao20010128nao** [comment]
@blackjack4494 I think I didn't receive the update, it doesn't happen to me.
Here's the json: https://gist.github.com/nao20010128nao/6c8239bfd40a89cfb3e2a8d57c59f769

**Review by blackjack4494 — APPROVED** [review]
there is still a minor issue that needs to be fixed tho.

**Pull request merged**
