### PR TITLE
[TMZ] Fix TMZ.com extractor

### PR DESCRIPTION
**Pull request by diegorodriguezv**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ x ] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [ x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ x ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ x ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This is a fix for the TMZ.com extractor. I did this on april 8 2020 but the PR never got merged in the original repo. Hopefully here it will be.
It seems TMZ started creating a new type of URL for its videos at the start of the year. These new URL's have some text before the ID, which broke the extractor.
Another problem was that the TMZ article pages changed their internal structure and the video URL is no longer in a json string but has to be obtained by parsing a JS line.
I tested the extractors today and they seem to be working OK.

### CODE REVIEW

**Comment by someziggyman** [comment]
Thanks for your work! Tried this video with your extractor file and it does not seam to be working.
https://www.tmz.com/videos/2020-10-31-103120-beverly-hills-protest-4878209/

maybe, tmz.py extractor file is not the only one that needs changes made? 
Here's the log:

./youtube-dlc -v -F https://www.tmz.com/videos/2020-10-31-103120-beverly-hills-protest-4878209/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.tmz.com/videos/2020-10-31-103120-beverly-hills-protest-4878209/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Kaltura] st_4878209: Downloading video info JSON
ERROR: An extractor error has occurred. (caused by KeyError(u'dataUrl',)); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dlc/youtube_dlc/extractor/kaltura.py", line 298, in _real_extract
    data_url = info['dataUrl']
KeyError: u'dataUrl'
Traceback (most recent call last):
  File "./youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dlc/youtube_dlc/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'dataUrl',)); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

**Comment by diegorodriguezv** [comment]
I'll check it out. Thanks for the feedback.

**Comment by diegorodriguezv** [comment]
Ok. It seems TMZ has changed again and introduced a new URL format for recent videos (october-2020 and newer). I'll try to add support to these new videos in another PR, but that doesn't mean that this PR has any defect. It adds support for videos posted between november-2019 and october-2020 which is useful.

**Comment by someziggyman** [comment]
> Ok. It seems TMZ has changed again and introduced a new URL format for recent videos (october-2020 and newer). I'll try to add support to these new videos in another PR, but that doesn't mean that this PR has any defect. It adds support for videos posted between november-2019 and october-2020 which is useful.

Sure. Thanks a lot. Appreciate your help with this!

**Comment by blackjack4494** [comment]
let me know when this is ready for review.

**Comment by diegorodriguezv** [comment]
Hello again. I investigated the new structure of tmz.com and found they now use JSON-LD in all their pages, so I fixed the extractor to take advantage of it. I tested it with old and recent pages and it seems to be working fine.

**Comment by someziggyman** [comment]
> Hello again. I investigated the new structure of tmz.com and found they now use JSON-LD in all their pages, so I fixed the extractor to take advantage of it. I tested it with old and recent pages and it seems to be working fine.

Wow! Brilliant! it seems to be working for every single TMZ link type.

But I've come across an interesting case. Not a big deal I guess, but still decided it's worth a highlight. 
https://www.tmz.com/2020/11/05/gervonta-davis-car-crash-hit-and-run-police/

It has an embedded Youtube link and below is some "Hot Video" section. I'm not sure, if there's some correct way to handle this and we can leave it as it is. 

Here's a log for it, if needed:
_./testdlc -v https://www.tmz.com/2020/11/05/gervonta-davis-car-crash-hit-and-run-police/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.tmz.com/2020/11/05/gervonta-davis-car-crash-hit-and-run-police/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[TMZ] https://www.tmz.com/2020/11/05/gervonta-davis-car-crash-hit-and-run-police/: Downloading webpage
WARNING: "url" field is missing or empty - skipping format, there is an error in extractor
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./testdlc/__main__.py", line 19, in <module>
  File "./testdlc/youtube_dlc/__init__.py", line 487, in main
  File "./testdlc/youtube_dlc/__init__.py", line 477, in _real_main
  File "./testdlc/youtube_dlc/YoutubeDL.py", line 2104, in download
  File "./testdlc/youtube_dlc/YoutubeDL.py", line 846, in extract_info
  File "./testdlc/youtube_dlc/YoutubeDL.py", line 901, in process_ie_result
  File "./testdlc/youtube_dlc/YoutubeDL.py", line 1641, in process_video_result
IndexError: list index out of range_

**Comment by diegorodriguezv** [comment]
Very thorough testing! Thanks.
I added support for embedded youtube and twitter videos. 
I'm guessing this PR is ready for review.

**Review by blackjack4494 — APPROVED** [review]

**Pull request merged**
