### PR TITLE
[youtube] "youtube.com/name" can be a user or a channel

### LINKED ISSUE #186: 404 Not Found for channel URL without /c/ or /channel/
## Verbose log

```
Y:\YouTube Channels\zSecurity>rem youtube-dl --cookies "Y:\cookies.txt" --add-metadata --write-description --write-info-json --write-thumbnail --download-archive "Y:\ytdl_archive.txt" --all-subs --sleep-interval 1 -ciw -o "%(title)s.%(ext)s" -v "https://www.youtube.com/zsecurity"

Y:\YouTube Channels\zSecurity>youtube-dl --cookies "Y:\cookies.txt" --add-metadata --write-description --write-info-json --write-thumbnail --download-archive "Y:\ytdl_archive.txt" --sleep-interval 1 -ciw -o "%(title)s.%(ext)s" -v "https://www.youtube.com/zsecurity"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'Y:\\cookies.txt', '--add-metadata', '--write-description', '--write-info-json', '--write-thumbnail', '--download-archive', 'Y:\\ytdl_archive.txt', '--sleep-interval', '1', '-ciw', '-o', '%(title)s.%(ext)s', '-v', 'https://www.youtube.com/zsecurity']
[debug] Loading archive file 'Y:\\ytdl_archive.txt'
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-2
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-04-15-51db0a4, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:user] zsecurity: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] zsecurity: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
  File "youtube_dlc\extractor\common.py", line 632, in _request_webpage
  File "youtube_dlc\YoutubeDL.py", line 2325, in urlopen
  File "urllib\request.py", line 523, in open
  File "urllib\request.py", line 632, in http_response
  File "urllib\request.py", line 555, in error
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 747, in http_error_302
  File "urllib\request.py", line 523, in open
  File "urllib\request.py", line 632, in http_response
  File "urllib\request.py", line 561, in error
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 641, in http_error_default
```

## Description

I'm using the latest `master` and found that I could not download a particular channel, yet the channel page works. The culprit seems to be that the URL I pasted lacks a channel path element. I added `/c/` before the channel name and it works, but the URL without that is also valid and should work.

### PR DESCRIPTION
**Pull request by pukkandan**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Direct youtube URLs (`youtube.com/name`) now doesn't have to be a username but [can be channel name](https://support.google.com/youtube/answer/6180214). Closes #186

### CODE REVIEW

**Comment by blackjack4494** [comment]
have no time to review it. maybe monday. maybe someone else can.

**Comment by someziggyman** [comment]
> have no time to review it. maybe monday. maybe someone else can.

Seems to be a legit fix and works fine for the cases described. Links like this: _https://www.youtube.com/zsecurity_ are going to work fine with this improvement. However, I'm not sure how it was generated. Clicking on various YouTube channels within YouTube all came up why a _/c/someChannelName_ - https://www.youtube.com/c/PeterSantenello
Doubt there's any risk approving and adding it to the next release. It works with all link formats, so it's definitely a good thing. Maybe, someone else can take a look and confirm with more expertise.

**Comment by pukkandan** [comment]
> However, I'm not sure how it was generated. Clicking on various YouTube channels within YouTube all came up why a /c/someChannelName or /channel/somechannelid

@someziggyman  Youtube allows to shorten /c/channelName to just /channelName. But they also allow /u/userName to /userName. So given a url such as /name, it not possible to tell whether it is a usename or a channel name. However, since all the code for downloading user and channel is the same, I just made it use the shortened URL itself for extraction. That way there is no need to know if it is a user page or channel page.

**Comment by pukkandan** [comment]
Made obsolete by #245

**Pull request closed without merging**
