### PR TITLE
RFC: youtube: Polymer UI and JSON endpoints for playlists

### LINKED ISSUE #148: youtube channel page downloads broken
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dlc version **2020.10.31**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
youtube-dlc.exe --ignore-config -i -o "%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s" --prefer-ffmpeg --merge-output-format mkv --write-sub --all-subs --convert-subs srt --add-metadata --write-description --write-annotations --write-all-thumbnails --write-info-json --cookies youtube-cookies.txt -v --proxy "" https://www.youtube.com/channel/UC7qPftDWPw9XuExpSgfkmJQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-i', '-o', '%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--add-metadata', '--write-description', '--write-annotations', '--write-all-thumbnails', '--write-info-json', '--cookies', 'youtube-cookies.txt', '-v', '--proxy', '', 'https://www.youtube.com/channel/UC7qPftDWPw9XuExpSgfkmJQ']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.07
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-04-24-a501947, ffprobe git-2020-04-24-a501947
[debug] Proxy map: {}
[youtube:channel] UC7qPftDWPw9XuExpSgfkmJQ: Downloading channel page
[youtube:playlist] UU7qPftDWPw9XuExpSgfkmJQ: Downloading webpage
[download] Downloading playlist: UU7qPftDWPw9XuExpSgfkmJQ
[youtube:playlist] playlist UU7qPftDWPw9XuExpSgfkmJQ: Downloading 0 videos
[download] Finished downloading playlist: UU7qPftDWPw9XuExpSgfkmJQ

```

## Description

youtube playlist downloads seem to have broken sometime within the last few hours. it was working earlier this morning, now all playlists result in "0 videos" from youtube-dlc. presumably youtube made a schema change which broke youtube-dlc.

Individual video downloads still work, for example this works perfectly:

youtube-dlc.exe --ignore-config -i -o "%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s" --prefer-ffmpeg --merge-output-format mkv --write-sub --all-subs --convert-subs srt --add-metadata --write-description --write-annotations --write-all-thumbnails --write-info-json --cookies youtube-cookies.txt -v --proxy "" https://www.youtube.com/watch?v=SXGAiTjFiMA

### PR DESCRIPTION
**Pull request by wlritchi**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

We already had a few copies of Polymer-style pagination handling logic for certain circumstances, but now we're forced into using it for all playlists since we can no longer disable Polymer. Refactor the logic to move it to the parent class for all entry lists (including e.g. search results, feeds, and list of playlists), and generify a bit to cover the child classes' use cases.

Fixes #148.

### CODE REVIEW

**Comment by wlritchi** [comment]
So far this is not tested for many use cases, including ones that we know will be affected (search, feeds, list of playlists). I've only tested it for downloading all of a channel's uploaded videos.

**Comment by someziggyman** [comment]
> So far this is not tested for many use cases, including ones that we know will be affected (search, feeds, list of playlists). I've only tested it for downloading all of a channel's uploaded videos.

Will test this fix with these IDs:
**Regular playlist ID:**
PLszW2az_oxFd7dFeCb1FFhk7c_eEer5n1
**Mix playlist ID:**
RDKR9wGi7gVLQ
**Search playlist:**
https://www.youtube.com/results?search_query=linkin+park+numb
**And channel playlist:**
https://www.youtube.com/user/TheLinuxFoundation/playlists

We now have two fixes released almost at the same time 
https://github.com/blackjack4494/yt-dlc/pull/150

**Comment by wlritchi** [comment]
See also #150 which appears to be doing essentially the same thing. There's a few things it does better than this one, including noticing that the base extractor already has a `_get_yt_initial_data` method and using that, rather than borrowing the copy from the search implementation. But I'm out of cycles for the night. Edits welcome!

**Comment by blackjack4494** [comment]
will merge #150 for now but that doesn't mean this PR will be obsolete then. Just being busy to take a deeper look.

**Comment by blackjack4494** [comment]
@wlritchi doesn't work with
`python3 -m youtube_dlc "https://www.youtube.com/results?search_query=linkin+park+numb" -F -v`
it will throw out error 
```
  File "D:\gitkraken\yt-dlc\youtube_dlc\__main__.py", line 19, in <module>
    youtube_dlc.main()
  File "D:\gitkraken\yt-dlc\youtube_dlc\__init__.py", line 487, in main
    _real_main(argv)
  File "D:\gitkraken\yt-dlc\youtube_dlc\__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "D:\gitkraken\yt-dlc\youtube_dlc\YoutubeDL.py", line 2104, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "D:\gitkraken\yt-dlc\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "D:\gitkraken\yt-dlc\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "D:\gitkraken\yt-dlc\youtube_dlc\extractor\youtube.py", line 3450, in _real_extract
    data_json = self._process_initial_data(webpage)
AttributeError: 'YoutubeSearchURLIE' object has no attribute '_process_initial_data'
```

**Review by blackjack4494 — APPROVED** [review]

**Comment by wlritchi** [comment]
Ah, yup, that's definitely an artifact left over from refactoring. I had intended to let search just process the initial data without requesting any further pages (which I think matches what it did before), but specifying the number of pages to fetch is probably more useful. I think your change as presented above will cap all playlist downloads to the first page, though.

**Comment by blackjack4494** [comment]
> Ah, yup, that's definitely an artifact left over from refactoring. I had intended to let search just process the initial data without requesting any further pages (which I think matches what it did before), but specifying the number of pages to fetch is probably more useful. I think your change as presented above will cap all playlist downloads to the first page, though.

yup you are right. Haven't thought about it lol.

**Comment by wlritchi** [comment]
> > Ah, yup, that's definitely an artifact left over from refactoring. I had intended to let search just process the initial data without requesting any further pages (which I think matches what it did before), but specifying the number of pages to fetch is probably more useful. I think your change as presented above will cap all playlist downloads to the first page, though.
> 
> yup you are right. Haven't thought about it lol.
> Any idea @wlritchi ? D:
> this seems to work but well it's rather hacky
> `for page_num in (range(n) if n>0 else itertools.count(1)):`

Basically doing this except defaulting to None, and adjusting the counting so it always starts from 1 (convention: page 0 is the initial page and continuations start from 1). This way 0 can be passed to say "only download the initial page with no continuations". Also open to tweaking the counting so the initial page counts as page 1.

**Comment by wlritchi** [comment]
Oh, hmm, search with 0 continuations returns nothing. I thought it would be the first page of results.

**Comment by blackjack4494** [comment]
> Oh, hmm, search with 0 continuations returns nothing. I thought it would be the first page of results.

that's why `max_pages=5` is needed in `class YoutubeSearchURLIE`

**Comment by wlritchi** [comment]
Oh I see, YoutubeSearchIE has its own implementation of `_entries` still, which interprets the parameter differently. That should also be merged into the superclass - will do.

**Comment by blackjack4494** [comment]
> Oh I see, YoutubeSearchIE has its own implementation of `_entries` still, which interprets the parameter differently. That should also be merged into the superclass - will do.

i set it to 5 now. If you plan any more changes hold on for now. Will merge this into master and release it. really have to sleep, can barely keep my eyes open :o

**Comment by wlritchi** [comment]
> > Oh I see, YoutubeSearchIE has its own implementation of `_entries` still, which interprets the parameter differently. That should also be merged into the superclass - will do.
> 
> i set it to 5 now. If you plan any more changes hold on for now. Will merge this into master and release it. really have to sleep, can barely keep my eyes open :o

:+1: I'll put anything else on a separate branch since it's more maintenance/refactoring than bugfixing anyway. While I'm at it - thoughts on whether the initial page should be page 0, or page 1 (i.e. do most users prefer 0-based or 1-based indexing)?

**Comment by Fabian42** [comment]
I prefer 0-based index at least, but I'm a programmer, so maybe not very representative. I don't think that there is anything paginated with page numbers left on YouTube, but if there was, it would likely start at 1. Things like "--playlist-start" are already 1-based.

**Comment by ultrasound1372** [comment]
If things like --playlist-start are already 1 based then it should start at 1.

**Comment by tygore587** [comment]
@blackjack4494 There is a bug in here. Playlist title for the output format is not set correct and is always NA

**Pull request merged**
