### PR TITLE
[youtube] fix: extract mix playlist ids from ytInitialData (#33)

### LINKED ISSUE #33: [Broken]YT playlist - collected 0 ids
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ytdlc -v -F https://youtu.be/-gJaYKwreEc?list=RD-gJaYKwreEc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://youtu.be/-gJaYKwreEc?list=RD-gJaYKwreEc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RD-gJaYKwreEc - add --no-playlist to just download video -gJaYKwreEc
[youtube:playlist] RD-gJaYKwreEc: Downloading page 1 of Youtube mix
[download] Downloading playlist: RD-gJaYKwreEc
[youtube:playlist] playlist RD-gJaYKwreEc: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RD-gJaYKwreEc
```

## Description

test links:
https://www.youtube.com/watch?v=-gJaYKwreEc&feature=youtu.be&list=RD-gJaYKwreEc

https://youtu.be/-gJaYKwreEc?list=RD-gJaYKwreEc

Tried some other playlists and they seem to be fine.

Assume this could be a formatting problem of the initial link.
Opened that channel, navigated to playlists and took this link for that very same playlist wanted initially:
https://www.youtube.com/watch?v=-gJaYKwreEc&list=PLF-k_OIEn_PMQ4bYJGD1Jx1OUAM7zwaEH
It works. 
Please take a look and in case this is just a link formatting problem, just close this issue.

### PR DESCRIPTION
**Pull request by insaneracist**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

Fixes #33

### CODE REVIEW

**Comment by someziggyman** [comment]
Thanks you so much for your effort fixing this, but still getting Collected 0 video ids.

I've implemented your changes to the extractor, re-built from source and tried these mix ids:
RD-gJaYKwreEc
RDKobbM94mXbo

**Comment by insaneracist** [comment]
@someziggyman could you try running it with  `--write-pages "RD-gJaYKwreEc"` and attach the output .dump file?

**Comment by someziggyman** [comment]
> @someziggyman could you try running it with `--write-pages RD-gJaYKwreEc` and attach the output .dump file?

Sure, here it is.
[RD-gJaYKwreEc.zip](https://github.com/blackjack4494/yt-dlc/files/5464263/RD-gJaYKwreEc.zip)

**Comment by insaneracist** [comment]
@someziggyman thank you! 
Using your html as input, this code works for me (it extracts the video ids and starts downloading them). Could you possibly double check you compiled these changes in? Maybe also throw a `print("yes!")` in `youtube.py`

**Comment by someziggyman** [comment]
> @someziggyman thank you!
> Using your html as input, this code works for me (it extracts the video ids and starts downloading them). Could you possibly double check you compiled these changes in? Maybe also throw a `print("yes!")` in `youtube.py`

I'm 100% sure the changes are made and compiled correctly. I'm on MacOS and my Python version is 2.7.16.. Maybe, this could be the reason why it fails? Strange and confusing. Sorry for being a pain in the ass. Wonder if anyone else can test case this and report their behaviour.

**Review by blackjack4494 — APPROVED** [review]

**Comment by blackjack4494** [comment]
It is indeed working as it should.
@insaneracist you need to resolve conflicts.

**Comment by someziggyman** [comment]
Ok, guys. I'm confused. downloaded the latest release now. Still can not get mix playlist to work :-) I swear, I'm not stupid))
What am I doing wrong? Python version, MacOS? I removed cache dir, using no cache dir, restarted my Mac. Any ideas you can share to help are greatly appreciated. 

Here's my log:
yt-dlc-2020.10.31 user$ ./youtube-dlc -v --no-cache-dir -F RD-gJaYKwreEc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--no-cache-dir', u'-F', u'RD-gJaYKwreEc']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] RD-gJaYKwreEc: Downloading page 1 of Youtube mix
[download] Downloading playlist: RD-gJaYKwreEc
[youtube:playlist] playlist RD-gJaYKwreEc: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RD-gJaYKwreEc

**Comment by insaneracist** [comment]
@someziggyman, this isn't in the latest release. It will probably get merged into the next version.

**Comment by someziggyman** [comment]
> @someziggyman, this isn't in the latest release. It will probably get merged into the next version.

can you please share your working extractor py file, so that I could test it on my end. I know python is rather tricky with spaces, new lines and things like that. maybe, I've pasted the changes wrong.

**Comment by someziggyman** [comment]
Bingo! it now works with your recent python2 fix commit. Thank you so much for your hard work!

**Comment by insaneracist** [comment]
you were right, it was python2 unicode/str types. can you try this branch again?
"T-t-this time it will work..."

**Comment by someziggyman** [comment]
> you were right, it was python2 unicode/str types.
> "T-t-this time it will work..."

Bingo! it now works with your recent python2 fix commit. Thank you so much for your hard work!

**Review by blackjack4494 — APPROVED** [review]

**Pull request merged**
