### PR TITLE
[vlive] merge youtube-dl and add new url support

### PR DESCRIPTION
**Pull request by kyuyeunk**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This pull request solves `vlive.py` related problems mentioned in https://github.com/blackjack4494/yt-dlc/pull/245#issuecomment-731224262.

I've started with `vlive.py` code in current youtube_dl repository and improved it to support new url type (i.e., `https://www.vlive.tv/post/<postId>`).

The code determines if a url is old type or new type. And for fetching data, it uses `post/v1.0/officialVideoPost-<videoId>` for old type and `post/v1.0/post-<postId>` for new type.

Example of a new url is added in `_TESTS`.

### CODE REVIEW

**Comment by kyuyeunk** [comment]
@pukkandan This pull request should maintain code similarity to youtube_dl while also supporting new url type.

**Comment by pukkandan** [comment]
Wow, you work fast. Can you confirm if this closes #226, #221 and #222

Also, it makes #223, #224 and #227 obsolete, correct?

**Comment by kyuyeunk** [comment]
@pukkandan No, this does not closes #226, #221, and #222 nor makes #223, #224, and #227 obsolete.

Above mentioned issues/bugs are present in both youtube-dl and youtube-dlc versions.

This pull request merely maintains similarity with youtube-dl codebase while implementing a feature that was already implemented in youtube-dlc version (i.e., new url support). Therefore, the issues are also present in this pull request as well.

Pull requests #223, #224, and #227 solves above mentioned issues, so these pull requests are needed.

I'm not familiar with the contribution guidelines of this repo, but should I try to merge above mentioned pull requests into this pull request? Or is it better to maintain a separate pull requests?

**Comment by pukkandan** [comment]
I am also not sure. But if the earlier PRs can still be applied on top of this patch, I think it is best to keep the PRs seperate

**Comment by kyuyeunk** [comment]
> I am also not sure. But if the earlier PRs can still be applied on top of this patch, I think it is best to keep the PRs seperate

Thanks for the input. I will keep pull requests separate for now.

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/commit/836c810716cca64673b2cb85a2b489f2dd0a15ef

**Comment by kyuyeunk** [comment]
> Related: [ytdl-org/youtube-dl@836c810](https://github.com/ytdl-org/youtube-dl/commit/836c810716cca64673b2cb85a2b489f2dd0a15ef)

@pukkandan I can verify that the latest youtube-dl update makes this PR obsolete.
Also, it seems to fix issue #226 (making PR #227 obsolete).

I will close above mentioned PRs and issue when `vlive.py` changes of youtube-dl are incorporated into #245

However, issues #221 (PR #223) and #222 (PR #224) are still present.

**Comment by pukkandan** [comment]
Is it sufficient to replace the entire `vlive.py` with dl's version?

**Comment by pukkandan** [comment]
https://github.com/blackjack4494/yt-dlc/pull/245/commits/38d7028407b5db50e4d3c712d52b294ec1100c1f#diff-b99f3b79e6a574f95b452073e111b94319a697d80ba7e62528556dfe0498b7ec

**Comment by kyuyeunk** [comment]
> Is it sufficient to replace the entire `vlive.py` with dl's version?

@pukkandan Yes it is sufficient.

> 38d7028#diff-b99f3b79e6a574f95b452073e111b94319a697d80ba7e62528556dfe0498b7ec

I can confirm that this commit works as intended and makes this PR obsolete.
Therefore, I will close this PR.

**Pull request closed without merging**
