### PR TITLE
Merging youtube-dl

### LINKED ISSUE #271: Auto-translate subs not being scraped from YouTube
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.11.11-3**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Scripts>youtube-dlc --write-auto-sub  https://www.youtube.com/watch?v=XAqfFLtARZI
[debug] System config: []
[debug] User config: ['--verbose', '--sub-lang', 'en,EN,en-gb,en-GB,EN-GB,en-ca,en-CA,EN-CA,en-ie,en-IE,EN-IE,en-us,en-US,EN-US,eng,ENG,english,English,ENGLISH,subtitles', '--write-sub', '--write-auto-sub', '--write-thumbnail', '--write-all-thumbnails', '--embed-thumbnail', '--write-description', '--write-info-json', '--add-metadata', '--xattrs', '--ignore-errors', '--no-playlist', '--format', '(bestvideo+bestaudio/bestvideo)[protocol!*=m3u8]/bestvideo+bestaudio/best', '--batch-file', 'C:/Users/USERNAME/AppData/Roaming/youtube-dl/download-queue.txt', '--force-ipv4', '--cookies', 'C:/Users/USERNAME/common-info/cookies.txt', '--no-check-certificate', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', '--abort-on-unavailable-fragment', '--socket-timeout', '30', '--retries', '999', '--hls-prefer-native', '--merge-output-format', 'mkv', '--audio-quality', '0', '--cache-dir', 'C:/Users/USERNAME/AppData/Roaming/youtube-dl/cache', '--restrict-filenames', '--no-mtime', '--output', 'D:/Downloads/youtube-dl/%(extractor)s/%(title)s [%(resolution)s] [%(id)s] [f%(format_id)s].%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--write-auto-sub', 'https://www.youtube.com/watch?v=XAqfFLtARZI']
[debug] Batch file urls: []
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] XAqfFLtARZI: Downloading webpage
[youtube] Downloading just video XAqfFLtARZI because of --no-playlist
[youtube] XAqfFLtARZI: Looking for automatic captions
WARNING: Couldn't find automatic captions for XAqfFLtARZI
[...]
```

## Description

Auto-translated subs (via '`--write-auto-sub`') are not downloaded from YouTube. As a comparison, this function works properly in youtube-dl 2020.11.29. This is also apparent when using the '`--list-subs`' option, where youtube-dlc will respond for the example video with '`WARNING: Couldn't find automatic captions for XAqfFLtARZI`', but youtube-dl will respond with a list of 109 possible auto-translations.

### LINKED ISSUE #288: [Broken] JSON of YouTube's playlist download is different from youtube-dl
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dlc --ignore-errors --dump-json --flat-playlist https://www.youtube.com/user/OrangestarAS/playlists
```

## Description

This command works, but it does not produce the same output as `youtube-dl`. I apologise if this project is not looking to have feature parity with `youtube-dl`.

Output

```
{
  "_type": ""
  "url": "",
  "ie_key": ""
}
...
```

Expected Output

```
{
  "_type": ""
  "url": "",
  "ie_key": "",
  "id": "",
  "title": ""
}
...
```

It is missing the "id" and "title" fields

### PR DESCRIPTION
**Pull request by pukkandan**
~~I will periodically update this PR with the latest version of youtube-dl.~~ ~~This doesn't have to be merged right away. It can be merged once there are enough changes accumulated to justify it~~

Updated to: 2021.01.16

Closes #288, Closes #271
Makes #290 obsolete (Related #228)
Makes #298 obsolete

---

#### Commits that have't been merged
1. **[tiktok](https://github.com/ytdl-org/youtube-dl/commit/fb626c05867deab04425bad0c0b16b55473841a2)** - ytdl and dlc's tiktok extractors are quite different and I dont understand the extractor enough to properly resolve the conflicts. @GreyAlien502 or @merval might wanna have a look
1. **[hotstar](https://github.com/ytdl-org/youtube-dl/commit/bb38a1215718cdf36d73ff0a7830a64cd9fa37cc)**, **[stitcher](https://github.com/ytdl-org/youtube-dl/commit/bb38a1215718cdf36d73ff0a7830a64cd9fa37cc)** (**[+this](https://github.com/ytdl-org/youtube-dl/commit/a563c97c5cddf55f8989ed7ea8314ef78e30107f)**) - I am not sure how to resolve the conflicts
1.  **[\[youtube\] Improve age-gated videos extraction](https://github.com/ytdl-org/youtube-dl/commit/59d63d8d4aa82c7b1472d5b6a0f9f4e9c2893212)** - dlc has a better age gate bypass than ytdl. @blackjack4494 could check if any changes can be adapted from this commit.
1. **[\[youtube:tab\] Capture and output alerts](https://github.com/ytdl-org/youtube-dl/commit/5bd7ad2e811c9bda2e889156bc261a76e9f086ed)** - My own implementation of the same is better imo because it gets all alerts and reports them as warnings. yt-dl's implementation instead gets the alerts only if there was an error.
1. **[Switch to GitHub actions for CI](https://github.com/ytdl-org/youtube-dl/commit/a8b31505edbf4d9608b2d964b936b6720dcbb40d)** - ytdl has now switched to Github Actions instead of Travis

---

#### The following files are ignored:

```
.github/ISSUE_TEMPLATE/1_broken_site.md
.github/ISSUE_TEMPLATE/2_site_support_request.md
.github/ISSUE_TEMPLATE/3_site_feature_request.md
.github/ISSUE_TEMPLATE/4_bug_report.md
.github/ISSUE_TEMPLATE/5_feature_request.md
.github/workflows/ci.yml
devscripts/run_tests.bat
youtube_dlc/version.py
.travis.yml
Changelog
```

**PS**:
Since this repo has been inactive for a while, I have created my own fork [yt-dlp](https://github.com/pukkandan/yt-dlp). Merging youtube-dl with both this repo and mine separately is proving to be unnecessary extra work. So I won't update this PR anymore. If/when @blackjack4494 returns and merges this PR, I will create a new PR with any pending updates.

### CODE REVIEW

**Comment by nixxo** [comment]
it will probably conflict with #274

**Comment by pukkandan** [comment]
@nixxo whichever gets merged first, the other person can just resolve the conflicts

**Comment by pukkandan** [comment]
@blackjack4494 It seems that the travis are not running for any new PRs. Did you turn it off?

**Comment by nao20010128nao** [comment]
> @blackjack4494 It seems that travis is not running for any new PRs. Did you turn it off?

No, Travis now have a very tight limit.

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by merval** [comment]
Crap. I missed the mention here. I'll take a look at the TikTok commit when I get a chance

**Comment by pukkandan** [comment]
I have updated this PR to the latest version 2021.01.16. Since this repo has been inactive for a while, I have created my own fork [yt-dlp](https://github.com/pukkandan/yt-dlp). Merging youtube-dl with both this repo and mine is proving to be unnecessary extra work. So I won't update this PR anymore. If/when @blackjack4494 returns and merges this PR, I will create a new PR with any pending updates.

**Comment by pukkandan** [comment]
I am deleting this branch to keep yt-dlp clean. You can find a clone at https://github.com/pukkandan/yt-dlp/tree/merge-ytdl2

**Pull request closed without merging**
